# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  banner: <%= ENV["MYNA_BANNER"] %>
  client: <%= ENV["MYNA_CLIENT"] %>
  couch_encryption_key: <%= ENV["COUCH_ENCRYPTION_KEY"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  couch_domain: <%= ENV["COUCH_DOMAIN"] %>
  couch_username: <%= ENV["COUCH_USERNAME"] %>
  couch_password: <%= ENV["COUCH_PASSWORD"] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
